// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Auth(arg1:string):Promise<main.AuthResult>;

export function GetActiveEmail():Promise<main.ActiveEmail>;

export function Greet(arg1:string):Promise<string>;

export function Logout():Promise<main.Logout>;

export function Verify():Promise<main.Verify>;
